name: Bug Report
description: Report a bug or unexpected behavior in LexiSphere
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug. Please fill out the sections below so we can investigate.

  - type: input
    id: version
    attributes:
      label: Extension Version
      description: Found in the popup footer or chrome://extensions
      placeholder: "0.1.0"
    validations:
      required: true

  - type: input
    id: browser
    attributes:
      label: Browser and Version
      placeholder: "Chrome 132, Edge 132"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe the bug clearly. What did you expect vs what actually happened?
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Minimal steps to trigger the bug
      value: |
        1.
        2.
        3.
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Screenshots, console errors, site URL, or relevant configuration details
    validations:
      required: false
