name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for your suggestion. Please describe what you would like and why.

  - type: textarea
    id: problem
    attributes:
      label: What problem does this solve?
      description: Describe the use case or pain point
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How do you imagine this working?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any workarounds or other approaches you have tried
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Screenshots, mockups, or links to related issues
    validations:
      required: false
